version: '3'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  api:
    build:
      context: "./quizservice"
      dockerfile: "Dockerfile"
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/api/staticfiles/
    command: gunicorn quizservice.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
      - static_volume:/home/app/api/staticfiles/
    ports:
      - 80:80
    depends_on:
      - api
