# Generated by Django 4.2.6 on 2023-10-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очки'),
        ),
    ]
