# Generated by Django 4.2.6 on 2023-10-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restquiz', '0002_alter_quiz_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryes',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
