# Generated by Django 4.2.6 on 2023-10-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restquiz', '0007_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='category', to='restquiz.categoryes', to_field='title', verbose_name='Категория'),
        ),
    ]
